export enum Role {
  EXECUTIVE = 'EXECUTIVE',
  SECRETARY = 'SECRETARY',
  PARENT = 'PARENT',
  PARENTAL_ASSISTANT = 'PARENTAL_ASSISTANT',
  TEACHER = 'TEACHER',
  DOCTOR = 'DOCTOR',
  PSYCHOLOGIST = 'PSYCHOLOGIST',
  NURSE = 'NURSE',
  SERVICE_DRIVER = 'SERVICE_DRIVER',
  SERVICE_ATTENDANT = 'SERVICE_ATTENDANT',
}
